# Generated by Django 6.0.1 on 2026-04-08 16:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='IAI-Cameroun Centre de Douala', max_length=100)),
                ('adresse', models.TextField(help_text='PK9, Douala - Station MRS, avant boulangerie Saker')),
                ('latitude', models.FloatField(default=4.051056)),
                ('longitude', models.FloatField(default=9.767865)),
                ('telephone', models.CharField(default='+237 242 58 79 52', max_length=20)),
                ('email', models.EmailField(default='contact@iai-cameroun.com', max_length=254)),
                ('horaires', models.CharField(default='Lundi-Vendredi: 07h30 - 16h30', max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Indications pour accéder au campus')),
            ],
            options={
                'verbose_name': 'Localisation du campus',
                'verbose_name_plural': 'Localisations du campus',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credit', models.PositiveIntegerField(default=3)),
                ('semestre', models.PositiveIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('volume_horaire', models.PositiveIntegerField(default=30)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_poi', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('BANQUE', 'Banque'), ('TRANSPORT', 'Transport'), ('HEBERGEMENT', 'Hébergement'), ('SANTE', 'Santé'), ('COMMERCE', 'Commerce'), ('RELIGIEUX', 'Lieu religieux'), ('ADMINISTRATIF', 'Service administratif')], max_length=20)),
                ('adresse', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('distance_approx', models.FloatField(blank=True, help_text='Distance approximative en mètres', null=True)),
                ('horaires', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': "Point d'intérêt",
                'verbose_name_plural': "Points d'intérêt",
            },
        ),
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('coefficient_default', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('est_actif', models.BooleanField(default=True)),
                ('couleur', models.CharField(default='#10B981', help_text="Couleur pour l'affichage", max_length=20)),
                ('icon', models.CharField(default='fa-chart-line', help_text='Icône Font Awesome', max_length=50)),
            ],
            options={
                'verbose_name': "Type d'Évaluation",
                'verbose_name_plural': "Types d'Évaluation",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('moyenne_semestre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credits_obtenus', models.PositiveIntegerField(default=0)),
                ('credits_totaux', models.PositiveIntegerField(default=0)),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('EXCLU', 'Exclu'), ('EN_ATTENTE', 'En Attente')], default='EN_ATTENTE', max_length=15)),
                ('mention', models.CharField(blank=True, max_length=20)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('effectif', models.PositiveIntegerField(blank=True, null=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='etudiants.etudiant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-annee_academique', 'semestre', '-moyenne_semestre'],
                'unique_together': {('etudiant', 'annee_academique', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('volume_horaire', models.PositiveIntegerField(default=30)),
                ('est_actif', models.BooleanField(default=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='etudiants.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='etudiants.niveau')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='notes.matiere')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_evaluation', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(default=120)),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('PREVUE', 'Prévue'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PREVUE', max_length=15)),
                ('est_publiee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='notes.cours')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_crees', to=settings.AUTH_USER_MODEL)),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.typeevaluation')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observation', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_validee', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.evaluation')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_saisie'],
                'permissions': [('peut_saisir_notes', 'Peut saisir des notes'), ('peut_valider_notes', 'Peut valider des notes'), ('peut_modifier_notes', 'Peut modifier des notes après validation'), ('peut_voir_notes_anonymes', 'Peut voir les notes anonymes')],
            },
        ),
        migrations.CreateModel(
            name='NoteAnonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_anonyme', models.CharField(max_length=20, unique=True)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('etudiant_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_anonymes', to='notes.evaluation')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note anonyme',
                'verbose_name_plural': 'Notes anonymes',
            },
        ),
        migrations.CreateModel(
            name='RecoursNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_actuelle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note_demandee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15)),
                ('decision', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recours', to='etudiants.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.evaluation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recours sur Note',
                'verbose_name_plural': 'Recours sur Notes',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='SessionAnonymat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_session', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('est_active', models.BooleanField(default=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_anonymat', to='notes.evaluation')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'anonymat",
                'verbose_name_plural': "Sessions d'anonymat",
            },
        ),
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('est_terminee', models.BooleanField(default=False)),
                ('proces_verbal', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.filiere')),
                ('membres', models.ManyToManyField(blank=True, related_name='deliberations', to=settings.AUTH_USER_MODEL)),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliberations_presidees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Délibération',
                'verbose_name_plural': 'Délibérations',
                'unique_together': {('filiere', 'annee_academique', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='DetailBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_tp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_matiere', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('credits_obtenus', models.PositiveIntegerField(default=0)),
                ('est_validee', models.BooleanField(default=False)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='notes.bulletin')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.matiere')),
            ],
            options={
                'verbose_name': 'Détail de Bulletin',
                'verbose_name_plural': 'Détails de Bulletins',
                'unique_together': {('bulletin', 'matiere')},
            },
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['annee_academique', 'semestre'], name='notes_cours_annee_a_ca22a7_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['filiere', 'niveau'], name='notes_cours_filiere_ecd417_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('matiere', 'filiere', 'niveau', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'evaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='noteanonyme',
            unique_together={('evaluation', 'code_anonyme')},
        ),
    ]
