# Generated by Django 5.0.2 on 2026-07-09 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0002_alter_documentetudiant_valide_par"),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cours",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cours_notes",
                to="etudiants.filiere",
            ),
        ),
        migrations.AlterField(
            model_name="cours",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cours_notes",
                to="notes.matiere",
            ),
        ),
        migrations.AlterField(
            model_name="cours",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cours_notes",
                to="etudiants.niveau",
            ),
        ),
    ]
