# Generated by Django 5.0.2 on 2026-07-13 01:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0004_formation_apprenant"),
        ("notes", "0002_alter_cours_filiere_alter_cours_matiere_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteApprenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Note / 20",
                    ),
                ),
                (
                    "date_evaluation",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'évaluation",
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Appréciation / Commentaire",
                    ),
                ),
                (
                    "apprenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_apprenant",
                        to="etudiants.apprenant",
                        verbose_name="Apprenant",
                    ),
                ),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_attribuees_apprenants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Formateur / Enseignant",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_apprenant",
                        to="etudiants.formation",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note Apprenant",
                "verbose_name_plural": "Notes Apprenants",
                "ordering": ["-date_evaluation"],
                "unique_together": {("apprenant", "formation")},
            },
        ),
    ]
