# Generated by Django 5.0.2 on 2026-07-24 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0005_alter_emploidutemps_unique_together_and_more"),
        ("etudiants", "0004_formation_apprenant"),
        ("notes", "0003_noteapprenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheNotesAnonymat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2025-2026", max_length=9),
                ),
                ("enseignant_nom", models.CharField(blank=True, max_length=150)),
                (
                    "fichier_fiche",
                    models.FileField(
                        blank=True, null=True, upload_to="fiches_anonymat/"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé / Importé"),
                        ],
                        default="BROUILLON",
                        max_length=15,
                    ),
                ),
                ("date_import", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiches_anonymat_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_anonymat",
                        to="cours.matiere",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_anonymat",
                        to="cours.salle",
                        verbose_name="Salle physique",
                    ),
                ),
                (
                    "type_evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_anonymat",
                        to="notes.typeevaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de Notes d'Anonymat",
                "verbose_name_plural": "Fiches de Notes d'Anonymat",
                "ordering": ["-date_import"],
            },
        ),
        migrations.CreateModel(
            name="LigneFicheNotesAnonymat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_anonymat", models.CharField(max_length=20)),
                (
                    "note",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("nom_manuscrit_detecte", models.CharField(blank=True, max_length=255)),
                (
                    "etudiant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lignes_anonymat",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="notes.fichenotesanonymat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Fiche d'Anonymat",
                "verbose_name_plural": "Lignes de Fiche d'Anonymat",
                "ordering": ["numero_anonymat"],
            },
        ),
    ]
