# Generated by Django 5.0.2 on 2026-07-24 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_fichenotesanonymat_lignefichenotesanonymat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcesVerbalNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                ("est_transmis", models.BooleanField(default=False)),
                ("date_transmission", models.DateTimeField(blank=True, null=True)),
                (
                    "fichier_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="proces_verbaux/"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pvs_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiche_anonymat",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proces_verbal",
                        to="notes.fichenotesanonymat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procès-verbal de Notes",
                "verbose_name_plural": "Procès-verbaux de Notes",
                "ordering": ["-date_generation"],
            },
        ),
    ]
