# Generated by Django 5.0.2 on 2026-07-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0004_formation_apprenant"),
        ("notes", "0005_procesverbalnotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniteEnseignement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=150)),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ues",
                        to="etudiants.filiere",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ues",
                        to="etudiants.niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unité d'Enseignement",
                "verbose_name_plural": "Unités d'Enseignement",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="matiere",
            name="unite_enseignement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matieres",
                to="notes.uniteenseignement",
            ),
        ),
    ]
