# Generated by Django 5.0.2 on 2026-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_uniteenseignement_matiere_unite_enseignement"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="absences",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="date_publication",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="discipline",
            field=models.CharField(default="-", max_length=50),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="est_publie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="moyenne_classe_generale",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="moyenne_classe_max",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="moyenne_classe_min",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="numero_bulletin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="bulletins/%Y/"),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="retards",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
