# Generated by Django 5.0.2 on 2026-08-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0008_campagneevaluation_questionevaluation_and_more"),
        ("etudiants", "0006_etudiant_date_concours_and_more"),
        ("notes", "0007_bulletin_absences_bulletin_date_publication_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fichenotesanonymat",
            options={
                "ordering": ["-date_creation"],
                "verbose_name": "Fiche de Notes d'Anonymat",
                "verbose_name_plural": "Fiches de Notes d'Anonymat",
            },
        ),
        migrations.RenameField(
            model_name="fichenotesanonymat",
            old_name="date_import",
            new_name="date_creation",
        ),
        migrations.AddField(
            model_name="fichenotesanonymat",
            name="date_transmission_anonymat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fichenotesanonymat",
            name="date_transmission_etudes",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fichenotesanonymat",
            name="enseignant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiches_anonymat_enseignant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fichenotesanonymat",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiches_anonymat",
                to="etudiants.filiere",
            ),
        ),
        migrations.AddField(
            model_name="fichenotesanonymat",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiches_anonymat",
                to="etudiants.niveau",
            ),
        ),
        migrations.AddField(
            model_name="lignefichenotesanonymat",
            name="score_ocr",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="procesverbalnotes",
            name="date_validation_chef_etudes",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="procesverbalnotes",
            name="est_valide_par_chef_etudes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="procesverbalnotes",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pvs_notes",
                to="etudiants.filiere",
            ),
        ),
        migrations.AddField(
            model_name="procesverbalnotes",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pvs_notes",
                to="cours.matiere",
            ),
        ),
        migrations.AddField(
            model_name="procesverbalnotes",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pvs_notes",
                to="etudiants.niveau",
            ),
        ),
        migrations.AddField(
            model_name="procesverbalnotes",
            name="salle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pvs_notes",
                to="cours.salle",
            ),
        ),
        migrations.AlterField(
            model_name="fichenotesanonymat",
            name="salle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiches_anonymat",
                to="cours.salle",
                verbose_name="Salle / Classe physical",
            ),
        ),
        migrations.AlterField(
            model_name="fichenotesanonymat",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "📝 Brouillon (Enseignant)"),
                    ("TRANSMIS_CHEF_ANONYMAT", "📨 Transmis au Chef de l'Anonymat"),
                    ("MATCH_EFFECTUE", "🔍 Matching Effectué (Chef Anonymat)"),
                    ("PV_GENERE", "📋 PV de Notes Généré"),
                    ("TRANSMIS_CHEF_ETUDES", "📩 Transmis au Chef des Études"),
                    ("VALIDE", "✅ Validé & Publié"),
                ],
                default="BROUILLON",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="procesverbalnotes",
            name="est_transmis",
            field=models.BooleanField(
                default=False, verbose_name="Transmis au Chef des Études"
            ),
        ),
    ]
