# Generated by Django 5.0.2 on 2026-08-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_alter_fichenotesanonymat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignefichenotesanonymat",
            name="moyenne_cc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="lignefichenotesanonymat",
            name="note_1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="lignefichenotesanonymat",
            name="note_2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="lignefichenotesanonymat",
            name="note_3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="lignefichenotesanonymat",
            name="note_4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="lignefichenotesanonymat",
            name="note_5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
