# Generated by Django 5.0.2 on 2026-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_lignefichenotesanonymat_moyenne_cc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichenotesanonymat",
            name="mode_fiche",
            field=models.CharField(
                choices=[
                    (
                        "EXPOSE_TP_TD",
                        "📋 Exposés, TP, TD & CC Continu (Noms, Matricules & Notes CC 1..5)",
                    ),
                    (
                        "DEVOIR_SUR_TABLE",
                        "🔒 Devoir sur Table / Examen (Anonymat 3 colonnes : Code + Note)",
                    ),
                ],
                default="EXPOSE_TP_TD",
                max_length=30,
                verbose_name="Mode / Nature de la Fiche",
            ),
        ),
    ]
