# Generated by Django 5.0.2 on 2026-08-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0012_matiereformation"),
        ("etudiants", "0006_etudiant_date_concours_and_more"),
        ("notes", "0010_fichenotesanonymat_mode_fiche"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="noteapprenant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="noteapprenant",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes_apprenant",
                to="cours.matiereformation",
                verbose_name="Matière",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noteapprenant",
            unique_together={("apprenant", "formation", "matiere")},
        ),
    ]
