# Generated by Django 5.0.2 on 2026-08-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0007_etudiant_verification_token"),
        ("notes", "0011_alter_noteapprenant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procesverbalnotes",
            name="annee_academique",
            field=models.CharField(default="2025-2026", max_length=9),
        ),
        migrations.CreateModel(
            name="LigneProcesVerbalNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_cc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_examen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_rattrapage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_finale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("note_cc_manquante", models.BooleanField(default=False)),
                ("note_examen_manquante", models.BooleanField(default=False)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_pv",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "pv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="notes.procesverbalnotes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Procès-Verbal de Notes",
                "verbose_name_plural": "Lignes de Procès-Verbal de Notes",
                "ordering": ["etudiant__nom", "etudiant__prenom"],
                "unique_together": {("pv", "etudiant")},
            },
        ),
    ]
