# Generated by Django 5.0.2 on 2026-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0012_procesverbalnotes_annee_academique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ligneprocesverbalnotes",
            name="note_1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="ligneprocesverbalnotes",
            name="note_2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="ligneprocesverbalnotes",
            name="note_3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="ligneprocesverbalnotes",
            name="note_4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="ligneprocesverbalnotes",
            name="note_5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
