# Generated by Django 5.0.2 on 2026-09-05 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0013_ligneprocesverbalnotes_note_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailbulletin",
            name="note_rattrapage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="semestre",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
