# Generated by Django 5.0.2 on 2026-07-13 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=150, verbose_name="Titre / Objet"),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("SCOLARITE", "Scolarité"),
                            ("ETUDES", "Diplômes et Attestations"),
                            ("ANONYMAT", "Revendication de notes"),
                            ("COMPTABILITE", "Paiements"),
                        ],
                        max_length=20,
                        verbose_name="Nature de la requête",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True,
                        help_text="PDF, JPG, PNG (max 5MB)",
                        null=True,
                        upload_to="requetes/pieces_jointes/%Y/%m/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SOUMIS", "Soumise"),
                            ("EN_COURS", "En cours de traitement"),
                            ("ESCALADE", "Escaladée au Directeur"),
                            ("RENVOYE", "Renvoyée au personnel"),
                            ("TRAITE", "Traitée / Répondue"),
                        ],
                        default="SOUMIS",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reponse",
                    models.TextField(
                        blank=True, default="", verbose_name="Réponse finale"
                    ),
                ),
                (
                    "reponse_interne",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Notes / Réponses internes (Directeur)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "historique",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Historique de suivi"
                    ),
                ),
                (
                    "assigne_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requetes_assignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignée à",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requetes_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de la requête",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requête",
                "verbose_name_plural": "Requêtes",
                "ordering": ["-date_creation"],
            },
        ),
    ]
