# Generated by Django 6.0.1 on 2026-03-29 13:13

import apps.etudiants.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format: 2024-2025', max_length=9, unique=True, verbose_name='Année académique')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_active', models.BooleanField(default=False, verbose_name='Est active')),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('GL', 'Génie Logiciel'), ('SR', 'Systèmes et Réseaux')], max_length=2, unique=True, verbose_name='Code filière')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree_ans', models.PositiveIntegerField(default=2, help_text='Durée de formation en années (DTS: 2 ans)', verbose_name='Durée (années)')),
                ('est_active', models.BooleanField(default=True, verbose_name='Est active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('effectif_max', models.PositiveIntegerField(default=40, verbose_name='Effectif maximum')),
                ('effectif_actuel', models.PositiveIntegerField(default=0, verbose_name='Effectif actuel')),
                ('est_active', models.BooleanField(default=True, verbose_name='Est active')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etudiants.anneeacademique', verbose_name='Année académique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etudiants.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['filiere__code', 'niveau__numero', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Format: GL.CMR.D014.2324A ou SR.CMR.D014.2324A', max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(choices=[('CMR', 'Camerounaise'), ('CIV', 'Ivoirienne'), ('SEN', 'Sénégalaise'), ('GAB', 'Gabonaise'), ('TCD', 'Tchadienne'), ('RCA', 'Centrafricaine'), ('COG', 'Congolaise'), ('GIN', 'Guinéenne'), ('BEN', 'Béninoise'), ('TGO', 'Togolaise'), ('FRA', 'Française'), ('BEL', 'Belge'), ('CAN', 'Canadienne'), ('USA', 'Américaine'), ('CHN', 'Chinoise'), ('AUT', 'Autre')], default='CMR', max_length=3, verbose_name='Nationalité')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Numéro de téléphone invalide')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('statut', models.CharField(choices=[('PREINSCRIT', 'Pré-inscrit'), ('INSCRIT', 'Inscrit'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('DIPLOME', 'Diplômé'), ('ABANDON', 'Abandon')], default='PREINSCRIT', max_length=10, verbose_name='Statut')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.etudiants.models.photo_etudiant_path, verbose_name='Photo')),
                ('recu_preinscription', models.FileField(blank=True, null=True, upload_to='etudiants/recus/preinscription/', verbose_name='Reçu de pré-inscription')),
                ('recu_preinscription_valide', models.BooleanField(default=False, verbose_name='Reçu de pré-inscription validé')),
                ('carte_etudiant_delivree', models.BooleanField(default=False, verbose_name="Carte d'étudiant délivrée")),
                ('date_delivrance_carte', models.DateField(blank=True, null=True, verbose_name='Date de délivrance carte')),
                ('nom_tuteur', models.CharField(max_length=100, verbose_name='Nom du tuteur')),
                ('telephone_tuteur', models.CharField(max_length=20, verbose_name='Téléphone du tuteur')),
                ('email_tuteur', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du tuteur')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, null=True, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('informations_medicales', models.TextField(blank=True, null=True, verbose_name='Informations médicales')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='etudiants.anneeacademique', verbose_name='Année académique')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='etudiants.classe', verbose_name='Classe')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='etudiants.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['nom', 'prenom'],
                'permissions': [('peut_exporter_etudiants', 'Peut exporter la liste des étudiants'), ('peut_importer_etudiants', 'Peut importer des étudiants'), ('peut_valider_recus', 'Peut valider les reçus de paiement'), ('peut_inscrire_etudiants', 'Peut inscrire des étudiants')],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('INSCRIPTION', 'Inscription'), ('PAIEMENT', 'Paiement'), ('CHANGEMENT_CLASSE', 'Changement de classe'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('DOCUMENT_AJOUTE', 'Document ajouté'), ('DOCUMENT_VALIDE', 'Document validé'), ('DOCUMENT_REJETE', 'Document rejeté'), ('RECU_VALIDE', 'Reçu validé'), ('RECU_REJETE', 'Reçu rejeté')], max_length=50, verbose_name='Action')),
                ('details', models.TextField(verbose_name='Détails')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique étudiant',
                'verbose_name_plural': 'Historique étudiants',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2')], verbose_name='Numéro du niveau')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='etudiants.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['filiere__code', 'numero'],
                'unique_together': {('numero', 'filiere')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='etudiants.niveau', verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='DocumentObligatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('EXTRAIT_NAISSANCE', 'Extrait de Naissance'), ('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('BAC', 'Diplôme BAC'), ('RELEVE_BAC', 'Relevé de Notes BAC'), ('PHOTO', "Photo d'Identité"), ('CERTIFICAT_MEDICAL', 'Certificat Médical'), ('CV', 'Curriculum Vitae'), ('LETTRE_MOTIVATION', 'Lettre de Motivation'), ('RECOMMANDATION', 'Lettre de Recommandation'), ('AUTRE', 'Autre Document')], max_length=30, unique=True, verbose_name='Type de document')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('format_accepte', models.CharField(default='PDF, JPG, PNG', max_length=100, verbose_name='Formats acceptés')),
                ('taille_max_mb', models.PositiveIntegerField(default=5, verbose_name='Taille max (Mo)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Document actif')),
                ('est_obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_obligatoires_crees', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, help_text='Laisser vide pour toutes les filières', null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.filiere', verbose_name='Filière concernée')),
                ('niveau', models.ForeignKey(blank=True, help_text='Laisser vide pour tous les niveaux', null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.niveau', verbose_name='Niveau concerné')),
            ],
            options={
                'verbose_name': 'Document obligatoire',
                'verbose_name_plural': 'Documents obligatoires',
                'ordering': ['ordre_affichage', 'type_document'],
                'permissions': [('can_manage_documents', 'Peut gérer les documents obligatoires'), ('can_validate_documents', 'Peut valider les documents étudiants')],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etudiants.niveau', verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='DocumentEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('EXTRAIT_NAISSANCE', 'Extrait de Naissance'), ('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('BAC', 'Diplôme BAC'), ('RELEVE_BAC', 'Relevé de Notes BAC'), ('PHOTO', "Photo d'Identité"), ('CERTIFICAT_MEDICAL', 'Certificat Médical'), ('CV', 'Curriculum Vitae'), ('LETTRE_MOTIVATION', 'Lettre de Motivation'), ('RECOMMANDATION', 'Lettre de Recommandation'), ('RECU_PREINSCRIPTION', 'Reçu de Pré-inscription'), ('RECU_TRANCHE1', 'Reçu 1ère Tranche'), ('RECU_TRANCHE2', 'Reçu 2ème Tranche'), ('RECU_TRANCHE3', 'Reçu 3ème Tranche'), ('RELEVE_NOTES', 'Relevé de Notes'), ('AUTRE', 'Autre Document')], max_length=30, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='etudiants/documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_obligatoire', models.BooleanField(default=False, help_text="Ce document est-il requis pour l'inscription ?", verbose_name='Document obligatoire')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Est validé')),
                ('commentaire', models.TextField(blank=True, help_text='Motif de rejet ou remarques', verbose_name='Commentaire')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='etudiants.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Document étudiant',
                'verbose_name_plural': 'Documents étudiants',
                'ordering': ['-date_ajout'],
                'unique_together': {('etudiant', 'type_document')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee_academique')},
        ),
    ]
