# Generated by Django 5.0.2 on 2026-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0002_alter_documentetudiant_valide_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="nom_mere",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom de la mère"
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="nom_pere",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom du père"
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="telephone_mere",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Téléphone de la mère",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="telephone_pere",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone du père"
            ),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="nom_tuteur",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nom du tuteur"
            ),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="telephone_tuteur",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Téléphone du tuteur",
            ),
        ),
    ]
