# Generated by Django 5.0.2 on 2026-07-09 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0003_etudiant_nom_mere_etudiant_nom_pere_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_formation",
                    models.CharField(
                        choices=[
                            ("CERTIFICATION", "Formation de Certification"),
                            ("CONTINUE", "Formation Continue"),
                        ],
                        default="CERTIFICATION",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("SECRETARIAT", "Secrétariat bureautique et comptable"),
                            ("MARKETING", "Marketing digital"),
                            ("INFOGRAPHIE", "Infographie"),
                            ("MAINTENANCE", "Maintenance informatique"),
                            ("RESEAUX", "Réseaux informatiques"),
                            ("WEBMASTER", "Webmaster"),
                            ("MIJEF", "Formation continue MIJEF 2035"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "tarif",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tarif de la formation en FCFA",
                        max_digits=10,
                    ),
                ),
                ("est_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Formation de certification",
                "verbose_name_plural": "Formations de certification",
            },
        ),
        migrations.CreateModel(
            name="Apprenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=200)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "niveau_etude",
                    models.CharField(
                        blank=True,
                        help_text="Niveau d'étude actuel ou diplôme le plus élevé",
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact", models.CharField(max_length=20)),
                ("lieu_residence", models.CharField(max_length=150)),
                ("nom_pere", models.CharField(blank=True, max_length=100)),
                ("contact_pere", models.CharField(blank=True, max_length=20)),
                ("nom_mere", models.CharField(blank=True, max_length=100)),
                ("contact_mere", models.CharField(blank=True, max_length=20)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "reste_a_payer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "attestation",
                    models.FileField(
                        blank=True, null=True, upload_to="apprenants/attestations/"
                    ),
                ),
                (
                    "dqp",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="apprenants/dqp/",
                        verbose_name="Diplôme de Qualification Professionnelle",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_apprenant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formations",
                    models.ManyToManyField(
                        blank=True, related_name="apprenants", to="etudiants.formation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Apprenant",
                "verbose_name_plural": "Apprenants",
            },
        ),
    ]
