# Generated by Django 5.0.2 on 2026-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0005_etudiant_est_actif"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="date_concours",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date du concours"
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="date_premiere_rentree",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date de première rentrée académique",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="lieu_residence",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Lieu de résidence"
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="pays_naissance",
            field=models.CharField(
                blank=True,
                default="Cameroun",
                max_length=100,
                verbose_name="Pays de naissance",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="personne_contact_nom_prenom",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Personne à contacter (Nom & Prénom)",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="personne_contact_residence",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Lieu de résidence de la personne à contacter",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="personne_contact_telephone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                verbose_name="Téléphone de la personne à contacter",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="region_origine",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Région d'origine"
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="serie_bacc",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Série / Type BACC"
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="situation_matrimoniale",
            field=models.CharField(
                blank=True,
                default="Célibataire",
                max_length=50,
                verbose_name="Situation matrimoniale",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="statut_etudiant_fiche",
            field=models.CharField(
                blank=True,
                default="Nouvelle admission",
                max_length=50,
                verbose_name="Statut étudiant sur fiche",
            ),
        ),
    ]
