# Generated by Django 5.0.2 on 2026-08-24 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0006_etudiant_date_concours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="verification_token",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Jeton de vérification QR",
            ),
        ),
    ]
