# Generated by Django 6.0.1 on 2026-03-29 13:15

import apps.paiements.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recu_fichier', models.FileField(help_text='Format acceptés: PDF, JPG, PNG (max 5MB)', upload_to=apps.paiements.models.recu_upload_path, verbose_name='Reçu bancaire')),
                ('date_televersement', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('montant_mentionne', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant mentionné sur le reçu')),
                ('reference_recu', models.CharField(blank=True, help_text='Référence bancaire mentionnée sur le reçu', max_length=100, verbose_name='Référence du reçu')),
                ('date_paiement', models.DateField(blank=True, help_text='Date de paiement mentionnée sur le reçu', null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('IA_VERIFIE', 'Vérifié par IA'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('DUPLICATA', 'Duplicata')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de vérification')),
                ('commentaires', models.TextField(blank=True, help_text='Commentaires sur la vérification', verbose_name='Commentaires')),
                ('score_confiance', models.FloatField(blank=True, help_text='Score entre 0 et 1 (1 = très fiable)', null=True, verbose_name='Score de confiance IA')),
                ('anomalies_detectees', models.JSONField(blank=True, default=dict, help_text="Anomalies détectées par l'IA", verbose_name='Anomalies détectées')),
                ('verification_ia', models.JSONField(blank=True, default=dict, help_text="Données extraites par l'IA", verbose_name='Résultat vérification IA')),
                ('ia_version', models.CharField(blank=True, help_text="Version du modèle d'IA utilisé", max_length=20, verbose_name='Version IA')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Reçu de paiement',
                'verbose_name_plural': 'Reçus de paiement',
                'ordering': ['-date_televersement'],
                'permissions': [('peut_verifier_recus', 'Peut vérifier les reçus de paiement'), ('peut_exporter_recus', 'Peut exporter les reçus'), ('peut_analyser_ia', "Peut utiliser l'IA pour analyser les reçus")],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TELEVERSEMENT', 'Téléversement'), ('IA_ANALYSE', 'Analyse IA'), ('VERIFICATION_MANUELLE', 'Vérification manuelle'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('DUPLICATA', 'Duplicata')], max_length=30, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('recu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='paiements.recupaiement', verbose_name='Reçu')),
            ],
            options={
                'verbose_name': 'Historique paiement',
                'verbose_name_plural': 'Historique paiements',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='TranchePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Pré-inscription'), (2, '1ère Tranche'), (3, '2ème Tranche'), (4, '3ème Tranche')], verbose_name='Numéro de la tranche')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('date_limite', models.DateField(verbose_name='Date limite de paiement')),
                ('annee_academique', models.CharField(help_text='Format: 2024-2025', max_length=20, verbose_name='Année académique')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Tranche active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Tranche de paiement',
                'verbose_name_plural': 'Tranches de paiement',
                'ordering': ['numero'],
                'unique_together': {('numero', 'annee_academique')},
            },
        ),
        migrations.AddField(
            model_name='recupaiement',
            name='tranche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='paiements.tranchepaiement', verbose_name='Tranche de paiement'),
        ),
    ]
