# Generated by Django 5.0.2 on 2026-07-19 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionConcours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Session de Juin 2026, Session d'Août 2026",
                        max_length=100,
                        verbose_name="Nom de la session",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex: SESS_JUIN_2026",
                        max_length=30,
                        unique=True,
                        verbose_name="Code unique",
                    ),
                ),
                (
                    "date_concours",
                    models.DateField(verbose_name="Date d'organisation du concours"),
                ),
                (
                    "annee_academique",
                    models.CharField(
                        default="2024-2025",
                        max_length=20,
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Session active"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description / Remarques"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Session de Concours (Niveau 1)",
                "verbose_name_plural": "Sessions de Concours (Niveau 1)",
                "ordering": ["date_concours"],
            },
        ),
        migrations.CreateModel(
            name="EcheanceSessionNiveau1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tranche_numero",
                    models.IntegerField(
                        choices=[
                            (1, "Pré-inscription"),
                            (2, "1ère Tranche"),
                            (3, "2ème Tranche"),
                            (4, "3ème Tranche"),
                        ],
                        verbose_name="Tranche de paiement",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "date_limite",
                    models.DateField(verbose_name="Date limite de paiement"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Remarques / Conditions",
                    ),
                ),
                (
                    "session_concours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="echeances",
                        to="paiements.sessionconcours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Échéance Niveau 1 par Session",
                "verbose_name_plural": "Échéances Niveau 1 par Session",
                "ordering": ["session_concours", "tranche_numero"],
                "unique_together": {("session_concours", "tranche_numero")},
            },
        ),
    ]
