# Generated by Django 5.0.2 on 2026-07-20 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0004_formation_apprenant"),
        ("paiements", "0002_sessionconcours_echeancesessionniveau1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultatConcours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_table",
                    models.CharField(
                        help_text="N° Anonymat ou N° de dossier du candidat",
                        max_length=50,
                        verbose_name="N° de Table / Dossier",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Adresse Email",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "statut_admission",
                    models.CharField(
                        choices=[
                            ("ADMIS", "Admis"),
                            ("LISTE_ATTENTE", "Liste d'attente"),
                        ],
                        default="ADMIS",
                        max_length=20,
                        verbose_name="Statut d'admission",
                    ),
                ),
                (
                    "statut_preinscription",
                    models.CharField(
                        choices=[
                            ("NON_PAYE", "Non payé"),
                            ("PAYE", "Payé (50 000 FCFA)"),
                        ],
                        default="NON_PAYE",
                        max_length=20,
                        verbose_name="Statut Pré-inscription",
                    ),
                ),
                (
                    "date_importation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'importation"
                    ),
                ),
                (
                    "etudiant_cree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultat_concours",
                        to="etudiants.etudiant",
                        verbose_name="Profil Étudiant Associé",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="etudiants.filiere",
                        verbose_name="Filière d'affectation",
                    ),
                ),
                (
                    "importe_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importé par",
                    ),
                ),
                (
                    "session_concours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="paiements.sessionconcours",
                        verbose_name="Session de Concours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de Concours",
                "verbose_name_plural": "Résultats de Concours",
                "ordering": ["session_concours", "nom", "prenom"],
                "unique_together": {("session_concours", "numero_table")},
            },
        ),
    ]
