# Generated by Django 5.0.2 on 2026-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0003_resultatconcours"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultatconcours",
            name="statut_tranche2",
            field=models.CharField(
                choices=[("NON_PAYE", "Non payé"), ("PAYE", "Payé")],
                default="NON_PAYE",
                max_length=20,
                verbose_name="Statut 2ème Tranche",
            ),
        ),
        migrations.AddField(
            model_name="resultatconcours",
            name="statut_tranche3",
            field=models.CharField(
                choices=[("NON_PAYE", "Non payé"), ("PAYE", "Payé")],
                default="NON_PAYE",
                max_length=20,
                verbose_name="Statut 3ème Tranche",
            ),
        ),
        migrations.AlterField(
            model_name="resultatconcours",
            name="statut_preinscription",
            field=models.CharField(
                choices=[("NON_PAYE", "Non payé"), ("PAYE", "Payé (84 000 FCFA)")],
                default="NON_PAYE",
                max_length=20,
                verbose_name="Statut 1ère Tranche (Pré-inscription 84k)",
            ),
        ),
    ]
