# Generated by Django 5.0.2 on 2026-07-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0004_resultatconcours_statut_tranche2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultatconcours",
            name="statut_tranche4",
            field=models.CharField(
                choices=[("NON_PAYE", "Non payé"), ("PAYE", "Payé")],
                default="NON_PAYE",
                max_length=20,
                verbose_name="Statut 4ème Tranche",
            ),
        ),
    ]
