# Generated by Django 5.0.2 on 2026-07-22 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0004_formation_apprenant"),
        ("paiements", "0005_resultatconcours_statut_tranche4"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionPaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Identifiant unique généré par le système",
                        max_length=100,
                        unique=True,
                        verbose_name="ID Transaction (interne)",
                    ),
                ),
                (
                    "cinetpay_payment_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Token CinetPay",
                    ),
                ),
                (
                    "cinetpay_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID Transaction CinetPay",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SUCCESS", "Réussi"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "type_paiement",
                    models.CharField(
                        choices=[
                            ("PENALITE", "Pénalités de retard"),
                            ("SCOLARITE", "Frais de scolarité"),
                        ],
                        default="PENALITE",
                        max_length=20,
                        verbose_name="Type de paiement",
                    ),
                ),
                (
                    "operateur",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Opérateur (MTN/Orange)",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "payment_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de paiement CinetPay"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_confirmation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de confirmation"
                    ),
                ),
                (
                    "cinetpay_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Réponse complète de CinetPay pour audit",
                        verbose_name="Données brutes CinetPay",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_paiement",
                        to="etudiants.etudiant",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de paiement en ligne",
                "verbose_name_plural": "Transactions de paiement en ligne",
                "ordering": ["-date_creation"],
            },
        ),
    ]
