# Generated by Django 5.0.2 on 2026-07-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0006_transactionpaiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recupaiement",
            name="tranche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recus",
                to="paiements.tranchepaiement",
                verbose_name="Tranche de paiement",
            ),
        ),
    ]
