# Generated by Django 5.0.2 on 2026-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0007_alter_recupaiement_tranche"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultatconcours",
            name="date_generation_acces",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de génération des accès"
            ),
        ),
        migrations.AddField(
            model_name="resultatconcours",
            name="mot_de_passe_temp",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Mot de passe temporaire généré",
            ),
        ),
    ]
