# Generated by Django 5.0.2 on 2026-09-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0008_resultatconcours_date_generation_acces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpaiement',
            name='tranche_numero',
            field=models.IntegerField(blank=True, help_text='Numéro de la tranche visée (ex: 1, 2, 3)', null=True, verbose_name='Numéro de tranche'),
        ),
        migrations.AlterField(
            model_name='transactionpaiement',
            name='type_paiement',
            field=models.CharField(choices=[('PENALITE', 'Pénalités de retard'), ('SCOLARITE', 'Frais de scolarité'), ('CONCOURS', 'Frais de concours'), ('DOCUMENT', 'Frais de document administratif')], default='PENALITE', max_length=20, verbose_name='Type de paiement'),
        ),
    ]
