# Generated by Django 6.0.1 on 2026-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(blank=True, choices=[('ETUDIANT', 'Étudiant'), ('PROFESSEUR', 'Professeur'), ('ADMIN_PEDAGOGIQUE', 'Admin Pédagogique'), ('ADMIN_FINANCIER', 'Admin Financier'), ('ADMIN_SYSTEME', 'Admin Système')], max_length=20, null=True),
        ),
    ]
