# Generated by Django 6.0.1 on 2026-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='anomalies_detectees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_soumission_document',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_validation_document',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='document_justificatif',
            field=models.FileField(blank=True, null=True, upload_to='documents_inscription/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='score_confiance_ia',
            field=models.FloatField(default=0, help_text="Score de confiance de l'IA (0-1)"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_inscription',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('DOCUMENT_EN_COURS', 'Document en cours de vérification'), ('DOCUMENT_VALIDE', 'Document validé'), ('DOCUMENT_REJETE', 'Document rejeté'), ('COMPTE_ACTIF', 'Compte actif'), ('COMPTE_BLOQUE', 'Compte bloqué')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_document',
            field=models.CharField(blank=True, choices=[('RECU_BANCAIRE', 'Reçu de pré-inscription'), ('CONTRAT', 'Contrat de travail'), ('NOTE_SERVICE', 'Note de service')], max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='verification_ia',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
