# Generated by Django 6.0.1 on 2026-04-06 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_utilisateur_anomalies_detectees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_derniere_activite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière activité'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='notification_email',
            field=models.BooleanField(default=True, verbose_name='Recevoir les notifications par email'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/%Y/%m/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='theme',
            field=models.CharField(choices=[('clair', '☀️ Clair'), ('sombre', '🌙 Sombre'), ('systeme', '🖥️ Système')], default='clair', max_length=10, verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='annee_obtention_bac',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)], verbose_name="Année d'obtention du Bac"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='anomalies_detectees',
            field=models.JSONField(blank=True, default=list, verbose_name='Anomalies détectées'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_soumission_document',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission du document'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_validation_document',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation du document'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='document_justificatif',
            field=models.FileField(blank=True, help_text='PDF, JPG ou PNG - Max 5MB', null=True, upload_to='documents_inscription/%Y/%m/%d/', verbose_name='Document justificatif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, help_text='Format: XX.CMR.D014.XXXXA', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Format de matricule invalide. Exemple: GL.CMR.D014.2425A', regex='^(GL|SR|PA|PR)\\.CMR\\.D014\\.\\d{4}[A-Z]$')], verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='score_confiance_ia',
            field=models.FloatField(default=0, help_text="Score de confiance de l'IA (0-1)", verbose_name='Score de confiance IA'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='serie_baccalaureat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Série du Baccalauréat'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut_inscription',
            field=models.CharField(choices=[('EN_ATTENTE', '⏳ En attente de validation'), ('DOCUMENT_EN_COURS', '📄 Document en cours de vérification'), ('DOCUMENT_VALIDE', '✅ Document validé'), ('DOCUMENT_REJETE', '❌ Document rejeté'), ('COMPTE_ACTIF', '🟢 Compte actif'), ('COMPTE_BLOQUE', '🔴 Compte bloqué')], default='EN_ATTENTE', max_length=20, verbose_name="Statut d'inscription"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format attendu: 6XXXXXXXX ou 2XXXXXXXX', regex='^(6|2)\\d{8}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_baccalaureat',
            field=models.CharField(blank=True, choices=[('A', 'Baccalauréat A (Littéraire)'), ('A1', 'Baccalauréat A1 (Lettres)'), ('A2', 'Baccalauréat A2 (Philosophie)'), ('A3', 'Baccalauréat A3 (Langues)'), ('A4', 'Baccalauréat A4 (Arts)'), ('B', 'Baccalauréat B (Économique)'), ('C', 'Baccalauréat C (Mathématiques)'), ('D', 'Baccalauréat D (Sciences)'), ('E', 'Baccalauréat E (Sciences techniques)'), ('F', 'Baccalauréat F (Technique)'), ('G', 'Baccalauréat G (Gestion)'), ('TI', 'Bac Technique Industriel'), ('TC', 'Bac Technique Commercial'), ('AUTRE', 'Autre Baccalauréat')], max_length=10, null=True, verbose_name='Type de Baccalauréat'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_document',
            field=models.CharField(blank=True, choices=[('RECU_BANCAIRE', '📄 Reçu de pré-inscription'), ('CONTRAT', '📑 Contrat de travail'), ('NOTE_SERVICE', '📋 Note de service')], max_length=20, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(blank=True, choices=[('ETUDIANT', '🎓 Étudiant'), ('PROFESSEUR', '👨\u200d🏫 Professeur'), ('ADMIN_PEDAGOGIQUE', '📚 Admin Pédagogique'), ('ADMIN_FINANCIER', '💰 Admin Financier'), ('ADMIN_SYSTEME', '⚙️ Admin Système')], max_length=20, null=True, verbose_name="Type d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='verification_ia',
            field=models.JSONField(blank=True, default=dict, verbose_name='Résultats vérification IA'),
        ),
    ]
