# Generated by Django 6.0.1 on 2026-04-06 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentification', '0004_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_utilisateur', models.CharField(choices=[('ETUDIANT', '🎓 Étudiant'), ('PERSONNEL', '👔 Personnel')], max_length=20)),
                ('document', models.FileField(upload_to='demandes_inscription/%Y/%m/%d/')),
                ('type_document', models.CharField(choices=[('RECU_BANCAIRE', '📄 Reçu de pré-inscription'), ('CONTRAT', '📑 Contrat de travail'), ('NOTE_SERVICE', '📋 Note de service')], max_length=20)),
                ('filiere_souhaitee', models.CharField(blank=True, max_length=2, null=True)),
                ('type_baccalaureat', models.CharField(blank=True, max_length=10, null=True)),
                ('annee_obtention_bac', models.IntegerField(blank=True, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('verification_ia', models.JSONField(blank=True, default=dict)),
                ('score_confiance', models.FloatField(default=0)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', '⏳ En attente de vérification'), ('EN_COURS', '🔄 Vérification en cours'), ('VALIDE', '✅ Validé'), ('REJETE', '❌ Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('matricule_genere', models.CharField(blank=True, max_length=50, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['type_utilisateur', 'last_name', 'first_name'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['matricule'], name='authentific_matricu_5a90b3_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='authentific_email_639591_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['type_utilisateur', 'statut_inscription'], name='authentific_type_ut_f78a93_idx'),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_inscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
