# Generated by Django 5.0.2 on 2026-07-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentification",
            "0005_demandeinscription_alter_utilisateur_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="type_utilisateur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ETUDIANT", "🎓 Étudiant"),
                    ("APPRENANT", "🎒 Apprenant (Certifications)"),
                    ("PROFESSEUR", "👨\u200d🏫 Professeur"),
                    ("ENSEIGNANT", "👨\u200d🏫 Enseignant"),
                    ("ADMIN_PEDAGOGIQUE", "📚 Admin Pédagogique"),
                    ("ADMIN_FINANCIER", "💰 Admin Financier"),
                    ("CHEF_SCOLARITE", "🏫 Chef Scolarité"),
                    ("CHEF_ETUDES", "📚 Chef Études"),
                    ("CHEF_ANONYMAT", "🕵️ Chef Anonymat"),
                    ("CHEF_COMPTABILITE", "💰 Chef Comptabilité"),
                    ("ADMIN_SYSTEME", "⚙️ Admin Système"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
