# Generated by Django 5.0.2 on 2026-07-12 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0006_alter_utilisateur_type_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="matricule",
            field=models.CharField(
                blank=True,
                help_text="Format: XX.CMR.D014.XXXXA",
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format de matricule invalide. Exemples : GL.CMR.DO14.2425 ou CSE.CMR.D123.2026.A",
                        regex="^((GL|SR)\\.CMR\\.(D014|DO\\d{2})\\.\\d{4}[A-Z]?|[A-Z]{3}\\.CMR\\.D\\d{3}\\.\\d{4}\\.[A-Z])$",
                    )
                ],
                verbose_name="Matricule",
            ),
        ),
    ]
