# Generated by Django 5.0.2 on 2026-07-21 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0008_alter_utilisateur_type_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="matricule",
            field=models.CharField(
                blank=True,
                help_text="Format: XX.CMR.D014.XXXXA",
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format de matricule invalide. Exemples : GL.CMR.D043.2324A ou CSE.CMR.D123.2026.A",
                        regex="^((GL|SR)\\.CMR\\.(D\\d{3}|DO\\d{2}|D014)\\.\\d{4}[A-Z]?|[A-Z]{2,3}\\.CMR\\.D\\d{3}\\.\\d{4}\\.[A-Z])$",
                    )
                ],
                verbose_name="Matricule",
            ),
        ),
    ]
