# Generated by Django 5.0.2 on 2026-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0009_fix_matricule_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeinscription",
            name="niveau_souhaite",
            field=models.IntegerField(default=1, verbose_name="Niveau souhaité"),
        ),
    ]
