# Generated by Django 5.0.2 on 2026-08-11 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0010_demandeinscription_niveau_souhaite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="matricule",
            field=models.CharField(
                blank=True,
                help_text="Format: XX.CMR.D014.XXXXA",
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format de matricule invalide. Exemples : GL.CMR.D043.2324A ou CS-FC-2026-01",
                        regex="^((GL|SR)\\.CMR\\.(D\\d{3}|DO\\d{2}|D014)\\.\\d{4}[A-Z]?|[A-Z]{2,4}\\.CMR\\.D\\d{3}\\.\\d{4}\\.[A-Z]|CS-[A-Z0-9\\-_]+|[A-Za-z0-9\\-_]{3,30})$",
                    )
                ],
                verbose_name="Matricule",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="type_utilisateur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ETUDIANT", "🎓 Étudiant"),
                    ("APPRENANT", "🎒 Apprenant (Certifications)"),
                    ("FORMATEUR", "👨\u200d🏫 Formateur (Certifications)"),
                    ("PROFESSEUR", "👨\u200d🏫 Professeur"),
                    ("ENSEIGNANT", "👨\u200d🏫 Enseignant"),
                    (
                        "CHEF_FORMATION_CONTINUE",
                        "🎓 Chef Service Formation Continue & Certifiante",
                    ),
                    ("ADMIN_PEDAGOGIQUE", "📚 Admin Pédagogique"),
                    ("ADMIN_FINANCIER", "💰 Admin Financier"),
                    ("CHEF_SCOLARITE", "🏫 Chef Scolarité"),
                    ("CHEF_ETUDES", "📚 Chef Études"),
                    ("CHEF_ANONYMAT", "🕵️ Chef Anonymat"),
                    ("CHEF_COMPTABILITE", "💰 Chef Comptabilité"),
                    ("ADMIN_SYSTEME", "⚙️ Admin Système"),
                ],
                max_length=35,
                null=True,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
