# Generated by Django 5.0.2 on 2026-08-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0011_alter_utilisateur_matricule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="type_utilisateur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ETUDIANT", "🎓 Étudiant"),
                    ("APPRENANT", "🎒 Apprenant (Certifications)"),
                    ("FORMATEUR", "👨\u200d🏫 Formateur (Certifications)"),
                    ("PROFESSEUR", "👨\u200d🏫 Professeur"),
                    ("ENSEIGNANT", "👨\u200d🏫 Enseignant"),
                    (
                        "CHEF_FORMATION_CONTINUE",
                        "🎓 Chef Service Formation Continue & Certifiante",
                    ),
                    ("ADMIN_PEDAGOGIQUE", "📚 Admin Pédagogique"),
                    ("ADMIN_FINANCIER", "💰 Admin Financier"),
                    ("CHEF_SCOLARITE", "🏫 Chef Scolarité"),
                    ("CHEF_ETUDES", "📚 Chef Études"),
                    ("CHEF_ANONYMAT", "🕵️ Chef Anonymat"),
                    ("CHEF_COMPTABILITE", "💰 Chef Comptabilité"),
                    ("DIRECTEUR", "Directeur / Représentant Résident"),
                    ("ADMIN_SYSTEME", "⚙️ Admin Système"),
                ],
                max_length=35,
                null=True,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
