# Generated by Django 5.0.2 on 2026-09-10 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_alter_utilisateur_type_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format attendu : 6XXXXXXXX, 2XXXXXXXX ou format international (+237...)', regex='^\\+?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
    ]
