# Generated by Django 6.0.1 on 2026-03-29 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('IMPRESSION', 'Impression'), ('PAIEMENT', 'Paiement'), ('PENALITE', 'Pénalité appliquée')], max_length=20)),
                ('description', models.TextField()),
                ('module', models.CharField(max_length=50)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='AlertePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.CharField(choices=[('PREINSCRIPTION', 'Pré-inscription'), ('TRANCHE_1', '1ère Tranche'), ('TRANCHE_2', '2ème Tranche'), ('TRANCHE_3', '3ème Tranche')], max_length=20)),
                ('type_alerte', models.CharField(choices=[('ECHEANCE_PROCHAIN', 'Échéance proche'), ('RETARD', 'En retard'), ('PENALITE', 'Pénalité appliquée'), ('RAPPEL', 'Rappel')], max_length=20)),
                ('message', models.TextField()),
                ('montant_penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_envoyee', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_paiement', to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Alerte paiement',
                'verbose_name_plural': 'Alertes paiements',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('est_modifiable', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_important', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], default='INFO', max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.URLField(blank=True, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PenalitePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.CharField(choices=[('PREINSCRIPTION', 'Pré-inscription'), ('TRANCHE_1', '1ère Tranche'), ('TRANCHE_2', '2ème Tranche'), ('TRANCHE_3', '3ème Tranche')], max_length=20)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_limite', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('semaines_retard', models.PositiveIntegerField(default=0)),
                ('est_regle', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Pénalité de paiement',
                'verbose_name_plural': 'Pénalités de paiement',
                'ordering': ['-date_calcul'],
                'unique_together': {('etudiant', 'tranche')},
            },
        ),
        migrations.CreateModel(
            name='HistoriquePenalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_montant_penalite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nouveau_montant_penalite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancien_semaines_retard', models.PositiveIntegerField()),
                ('nouveau_semaines_retard', models.PositiveIntegerField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('raison', models.TextField(blank=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_penalites', to=settings.AUTH_USER_MODEL)),
                ('penalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='tableau_bord.penalitepaiement')),
            ],
            options={
                'verbose_name': 'Historique des pénalités',
                'verbose_name_plural': 'Historique des pénalités',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('EFFECTIFS', 'Effectifs Étudiants'), ('RESULTATS', 'Résultats Académiques'), ('FINANCIER', 'Rapport Financier'), ('PRESENCE', 'Rapport de Présence'), ('PAIEMENT', 'Rapport de Paiement'), ('PENALITES', 'Rapport des Pénalités'), ('STATISTIQUE', 'Rapport Statistique'), ('CUSTOM', 'Rapport Personnalisé')], max_length=15)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_archive', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.filiere')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_stat', models.CharField(choices=[('EFFECTIF_TOTAL', 'Effectif Total Étudiants'), ('EFFECTIF_FILIERE', 'Effectif par Filière'), ('EFFECTIF_NIVEAU', 'Effectif par Niveau'), ('TAUX_REUSSITE', 'Taux de Réussite'), ('TAUX_ECHEC', "Taux d'Échec"), ('TAUX_ABANDON', "Taux d'Abandon"), ('RECETTES', 'Recettes Totales'), ('RECETTES_PENALITES', 'Recettes avec Pénalités'), ('PENALITES_TOTALES', 'Total des Pénalités'), ('IMPAYES', 'Impayés'), ('MOYENNE_GENERALE', 'Moyenne Générale')], max_length=25, verbose_name='Type de statistique')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valeur_texte', models.CharField(blank=True, max_length=200)),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.PositiveIntegerField(blank=True, null=True)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.filiere')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=10)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À Faire'), ('EN_COURS', 'En Cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField()),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('module', models.CharField(choices=[('ETUDIANTS', 'Étudiants'), ('PROFESSEURS', 'Professeurs'), ('COURS', 'Cours'), ('NOTES', 'Notes'), ('INSCRIPTIONS', 'Inscriptions'), ('PAIEMENTS', 'Paiements'), ('GENERAL', 'Général')], default='GENERAL', max_length=50)),
                ('assignee_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('assignee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees_par', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-priorite', 'date_echeance'],
            },
        ),
    ]
