# Generated by Django 5.0.2 on 2026-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tableau_bord", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglementInterieur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        default="Règlement Intérieur IAI-Cameroun",
                        max_length=150,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="reglements/", verbose_name="Fichier PDF"
                    ),
                ),
                (
                    "date_televersement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de téléversement"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Règlement actif"),
                ),
            ],
            options={
                "verbose_name": "Règlement Intérieur",
                "verbose_name_plural": "Règlements Intérieurs",
                "ordering": ["-date_televersement"],
            },
        ),
    ]
