# Generated by Django 5.0.2 on 2026-07-24 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tableau_bord", "0002_reglementinterieur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField(blank=True, null=True)),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="notes_information/"
                    ),
                ),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                ("est_active", models.BooleanField(default=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_publiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Note d'Information",
                "verbose_name_plural": "Notes d'Information",
                "ordering": ["-date_publication"],
            },
        ),
    ]
