# Generated by Django 5.0.2 on 2026-08-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tableau_bord", "0003_noteinformation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("NOTES", "Saisie/Modification de Notes"),
                            ("PAIEMENT", "Validation/Rejet de Paiement"),
                            ("ANONYMAT", "Gestion de l'Anonymat"),
                            ("DELIBERATION", "Délibération du Jury"),
                            ("ETUDIANT", "Gestion des Étudiants"),
                            ("SECURITE", "Accès et Rôles"),
                        ],
                        default="NOTES",
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, null=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'Audit",
                "verbose_name_plural": "Journaux d'Audit",
                "ordering": ["-date_action"],
            },
        ),
    ]
