# Generated by Django 5.0.2 on 2026-07-09 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiants", "0002_alter_documentetudiant_valide_par"),
        ("professeurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_salle",
                    models.CharField(
                        choices=[
                            ("COURS", "Salle de Cours"),
                            ("TP", "Salle de TP"),
                            ("LABO", "Laboratoire"),
                            ("AMPHI", "Amphithéâtre"),
                            ("REUNION", "Salle de Réunion"),
                        ],
                        default="COURS",
                        max_length=10,
                    ),
                ),
                ("capacite", models.PositiveIntegerField(default=30)),
                ("etage", models.PositiveIntegerField(default=0)),
                (
                    "est_equipee",
                    models.BooleanField(
                        default=True, help_text="Est équipée pour les cours"
                    ),
                ),
                ("a_projecteur", models.BooleanField(default=False)),
                ("a_climatisation", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("est_disponible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Salle",
                "verbose_name_plural": "Salles",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "credits",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ("heures_cours", models.PositiveIntegerField(default=30)),
                ("heures_td", models.PositiveIntegerField(default=15)),
                ("heures_tp", models.PositiveIntegerField(default=0)),
                (
                    "semestre",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                ("est_optionnelle", models.BooleanField(default=False)),
                ("prerequis", models.ManyToManyField(blank=True, to="cours.matiere")),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "type_cours",
                    models.CharField(
                        choices=[
                            ("COURS", "Cours Magistral"),
                            ("TD", "Travaux Dirigés"),
                            ("TP", "Travaux Pratiques"),
                        ],
                        default="COURS",
                        max_length=10,
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2024-2025", max_length=9),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("Lundi", "Lundi"),
                            ("Mardi", "Mardi"),
                            ("Mercredi", "Mercredi"),
                            ("Jeudi", "Jeudi"),
                            ("Vendredi", "Vendredi"),
                            ("Samedi", "Samedi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("capacite_max", models.PositiveIntegerField(default=50)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cours",
                        to="etudiants.filiere",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cours_assignes",
                        to="professeurs.professeur",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cours",
                        to="cours.matiere",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cours.salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
                "ordering": ["code"],
                "unique_together": {
                    ("matiere", "filiere", "type_cours", "annee_academique")
                },
            },
        ),
        migrations.CreateModel(
            name="RessourceCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_ressource",
                    models.CharField(
                        choices=[
                            ("COURS", "Support de Cours"),
                            ("TD", "Sujet de TD"),
                            ("TP", "Sujet de TP"),
                            ("EXAMEN", "Sujet d'Examen"),
                            ("CORRIGE", "Corrigé"),
                            ("LIVRE", "Livre Recommandé"),
                            ("ARTICLE", "Article Scientifique"),
                            ("VIDEO", "Vidéo"),
                            ("LIEN", "Lien Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="cours/ressources/"
                    ),
                ),
                ("lien_externe", models.URLField(blank=True, null=True)),
                ("est_public", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ressources",
                        to="cours.cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource de Cours",
                "verbose_name_plural": "Ressources de Cours",
                "ordering": ["-date_ajout"],
            },
        ),
        migrations.CreateModel(
            name="SeanceCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "duree_heures",
                    models.DecimalField(decimal_places=2, default=2, max_digits=4),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField(blank=True)),
                (
                    "supports_cours",
                    models.FileField(
                        blank=True, null=True, upload_to="cours/supports/"
                    ),
                ),
                ("est_effectuee", models.BooleanField(default=False)),
                ("est_annulee", models.BooleanField(default=False)),
                ("motif_annulation", models.TextField(blank=True)),
                ("nombre_present", models.PositiveIntegerField(default=0)),
                ("nombre_absent", models.PositiveIntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seances",
                        to="cours.cours",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cours.salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance de Cours",
                "verbose_name_plural": "Séances de Cours",
                "ordering": ["-date", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="EmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2024-2025", max_length=9),
                ),
                ("semestre", models.PositiveIntegerField(default=1)),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="emplois_du_temps/"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emplois_du_temps",
                        to="etudiants.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emploi du Temps",
                "verbose_name_plural": "Emplois du Temps",
                "ordering": ["-annee_academique", "filiere"],
                "unique_together": {("filiere", "annee_academique", "semestre")},
            },
        ),
        migrations.CreateModel(
            name="InscriptionCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_cours",
                        to="cours.cours",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_cours",
                        to="etudiants.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription au Cours",
                "verbose_name_plural": "Inscriptions aux Cours",
                "unique_together": {("etudiant", "cours")},
            },
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("ABSENT", "Absent"),
                            ("RETARD", "En Retard"),
                            ("EXCUSE", "Excusé"),
                        ],
                        default="PRESENT",
                        max_length=10,
                    ),
                ),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="cours.seancecours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "unique_together": {("seance", "etudiant")},
            },
        ),
    ]
