# Generated by Django 5.0.2 on 2026-07-13 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportPedagogiqueApprenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre du document"),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("COURS", "Support de Cours"),
                            ("TD", "Sujet de TD"),
                            ("TP", "Sujet de TP"),
                        ],
                        max_length=10,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "type_formation",
                    models.CharField(
                        choices=[
                            ("CERTIFICATION", "Formation de Certification"),
                            ("CONTINUE", "Formation Continue"),
                            ("TOUS", "Toutes les Formations"),
                        ],
                        default="TOUS",
                        max_length=20,
                        verbose_name="Type de formation",
                    ),
                ),
                (
                    "module_formation",
                    models.CharField(
                        choices=[
                            ("SECRETARIAT", "Secrétariat bureautique et comptable"),
                            ("MARKETING", "Marketing digital"),
                            ("INFOGRAPHIE", "Infographie"),
                            ("MAINTENANCE", "Maintenance informatique"),
                            ("RESEAUX", "Réseaux informatiques"),
                            ("WEBMASTER", "Webmaster"),
                            ("MIJEF", "Formation continue MIJEF 2035"),
                            ("TOUS", "Tous les Modules"),
                        ],
                        default="TOUS",
                        max_length=50,
                        verbose_name="Module de formation",
                    ),
                ),
                (
                    "niveau_etude",
                    models.CharField(
                        blank=True,
                        help_text="Laisser vide pour tous les niveaux d'apprenants",
                        max_length=100,
                        verbose_name="Niveau d'étude",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="cours/apprenants/",
                        verbose_name="Fichier (PDF, ZIP, DOCX...)",
                    ),
                ),
                (
                    "date_depot",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de dépôt"
                    ),
                ),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supports_apprenants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Formateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Pédagogique Apprenant",
                "verbose_name_plural": "Supports Pédagogiques Apprenants",
                "ordering": ["-date_depot"],
            },
        ),
    ]
