# Generated by Django 5.0.2 on 2026-07-19 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0002_supportpedagogiqueapprenant"),
        ("etudiants", "0004_formation_apprenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploiDuTempsHebdomadaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("LEVEL_1", "Niveau 1 (LEVEL 1)"),
                            ("LEVEL_2", "Niveau 2 (LEVEL 2)"),
                        ],
                        default="LEVEL_1",
                        max_length=10,
                    ),
                ),
                (
                    "titre_semaine",
                    models.CharField(
                        help_text="Ex: SEMAINE: 11 MAI - 16 MAI 2026", max_length=100
                    ),
                ),
                ("date_debut_semaine", models.DateField()),
                ("date_fin_semaine", models.DateField()),
                (
                    "annee_academique",
                    models.CharField(default="2024-2025", max_length=9),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon (Chef des Études)"),
                            (
                                "EN_ATTENTE_VALIDATION",
                                "Soumis pour approbation au Directeur",
                            ),
                            ("VALIDE", "Approuvé & Publié (Directeur)"),
                            ("REJETE", "Rejeté / À réviser"),
                        ],
                        default="BROUILLON",
                        max_length=25,
                    ),
                ),
                ("date_approbation", models.DateTimeField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "approuve_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emplois_approuves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emplois_du_temps_hebdo",
                        to="etudiants.filiere",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emplois_du_temps",
                        to="cours.salle",
                    ),
                ),
                (
                    "soumis_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emplois_soumis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emploi du Temps Hebdomadaire",
                "verbose_name_plural": "Emplois du Temps Hebdomadaires",
                "ordering": ["-date_debut_semaine", "filiere"],
            },
        ),
        migrations.CreateModel(
            name="CreneauEmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("LUNDI", "Lundi"),
                            ("MARDI", "Mardi"),
                            ("MERCREDI", "Mercredi"),
                            ("JEUDI", "Jeudi"),
                            ("VENDREDI", "Vendredi"),
                            ("SAMEDI", "Samedi"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "plage",
                    models.CharField(
                        choices=[
                            ("P1", "07:30 - 09:30"),
                            ("P2", "09:30 - 11:30"),
                            ("PAUSE", "11:30 - 12:45 (PAUSE)"),
                            ("P3", "12:45 - 14:45"),
                            ("P4", "14:45 - 16:45"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "intitule",
                    models.CharField(
                        blank=True,
                        help_text="Ex: TP(TRAVAUX PRATIQUE), Devoir Séminaire",
                        max_length=200,
                    ),
                ),
                (
                    "enseignant_nom",
                    models.CharField(
                        blank=True,
                        help_text="Ex: M NNANGA, M DASSY, Mme MELLA",
                        max_length=100,
                    ),
                ),
                (
                    "salle_nom",
                    models.CharField(
                        blank=True, help_text="Ex: GL3D, Stadium", max_length=50
                    ),
                ),
                (
                    "progression_heures",
                    models.CharField(
                        blank=True, help_text="Ex: 28/30 hrs, 70/300 hrs", max_length=50
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("COURS", "Cours / TP standard (Bleu)"),
                            (
                                "EVALUATION",
                                "Devoir / Contrôle Continu (CA) / Rattrapage (Rose)",
                            ),
                            ("PAUSE", "Pause (Jaune)"),
                            ("AUTRE", "Autre (Sport, Activité)"),
                        ],
                        default="COURS",
                        max_length=20,
                    ),
                ),
                (
                    "emploi_du_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creneaux",
                        to="cours.emploidutempshebdomadaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau d'Emploi du Temps",
                "verbose_name_plural": "Créneaux d'Emploi du Temps",
                "unique_together": {("emploi_du_temps", "jour", "plage")},
            },
        ),
    ]
