# Generated by Django 5.0.2 on 2026-07-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0003_emploidutempshebdomadaire_creneauemploidutemps"),
        ("etudiants", "0004_formation_apprenant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emploidutemps",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emplois_du_temps",
                to="etudiants.classe",
            ),
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emplois_du_temps",
                to="etudiants.niveau",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emploidutemps",
            unique_together={
                ("filiere", "niveau", "classe", "annee_academique", "semestre")
            },
        ),
    ]
