# Generated by Django 5.0.2 on 2026-07-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0004_alter_emploidutemps_unique_together_and_more"),
        ("etudiants", "0004_formation_apprenant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emploidutemps",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="salle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emplois_pdf",
                to="cours.salle",
            ),
        ),
        migrations.RemoveField(
            model_name="emploidutemps",
            name="classe",
        ),
        migrations.AlterUniqueTogether(
            name="emploidutemps",
            unique_together={
                ("filiere", "niveau", "salle", "annee_academique", "semestre")
            },
        ),
    ]
