# Generated by Django 5.0.2 on 2026-08-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0005_alter_emploidutemps_unique_together_and_more"),
        ("etudiants", "0004_formation_apprenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FichePresenceHebdomadaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2025-2026", max_length=9),
                ),
                ("semaine_du", models.DateField()),
                ("semaine_au", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("PUBLIE", "Publié (Absences Cumulées)"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                (
                    "fichier_scan",
                    models.FileField(
                        blank=True, null=True, upload_to="presences/scans/"
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_presence",
                        to="etudiants.classe",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiches_presence_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_presence",
                        to="etudiants.filiere",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_presence",
                        to="etudiants.niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de Présence Hebdomadaire",
                "verbose_name_plural": "Fiches de Présence Hebdomadaires",
                "ordering": ["-semaine_du", "classe"],
            },
        ),
        migrations.CreateModel(
            name="LignePresenceHebdomadaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_absences", models.PositiveIntegerField(default=0)),
                (
                    "details_jours_json",
                    models.TextField(
                        default="{}", help_text="Stockage JSON des créneaux par jour"
                    ),
                ),
                ("est_cumulee", models.BooleanField(default=False)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_presence_hebdo",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="cours.fichepresencehebdomadaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Présence Hebdomadaire",
                "verbose_name_plural": "Lignes de Présence Hebdomadaires",
                "unique_together": {("fiche", "etudiant")},
            },
        ),
    ]
