# Generated by Django 5.0.2 on 2026-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0006_fichepresencehebdomadaire_lignepresencehebdomadaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignepresencehebdomadaire",
            name="heures_justifiees",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
