# Generated by Django 5.0.2 on 2026-08-10 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0007_lignepresencehebdomadaire_heures_justifiees"),
        ("etudiants", "0004_formation_apprenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampagneEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        help_text="Ex: Évaluation Pédagogique - Semestre 1 (2025-2026)",
                        max_length=200,
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2025-2026", max_length=9),
                ),
                (
                    "semestre",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("OUVERTE", "Ouverte aux étudiants"),
                            ("CLOTUREE", "Clôturée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Campagne d'Évaluation",
                "verbose_name_plural": "Campagnes d'Évaluation",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="QuestionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=255)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("PEDAGOGIE", "Qualité Pédagogique & Maîtrise du cours"),
                            ("PONCTUALITE", "Ponctualité & Assiduité"),
                            ("SUPPORTS", "Clarté des supports & TP/TD"),
                            ("INTERACTIVITE", "Interactivité & Écoute des étudiants"),
                            ("EVALUATION", "Évaluation & Respect du programme"),
                            ("GLOBAL", "Appréciation globale"),
                        ],
                        default="PEDAGOGIE",
                        max_length=20,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=1)),
                ("est_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Question d'Évaluation",
                "verbose_name_plural": "Questions d'Évaluation",
                "ordering": ["categorie", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="ReponseEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, help_text="Commentaire ou remarque anonyme"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="cours.campagneevaluation",
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_evaluation",
                        to="cours.cours",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="cours.questionevaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse d'Évaluation (Anonyme)",
                "verbose_name_plural": "Réponses d'Évaluation (Anonymes)",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="cours.campagneevaluation",
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations_evaluation",
                        to="cours.cours",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations_evaluation",
                        to="etudiants.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation Évaluation",
                "verbose_name_plural": "Participations Évaluations",
                "unique_together": {("campagne", "cours", "etudiant")},
            },
        ),
    ]
