# Generated by Django 5.0.2 on 2026-08-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0008_campagneevaluation_questionevaluation_and_more"),
        ("etudiants", "0006_etudiant_date_concours_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fichepresencehebdomadaire",
            unique_together={("classe", "semaine_du")},
        ),
    ]
