# Generated by Django 5.0.2 on 2026-08-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0009_alter_fichepresencehebdomadaire_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressourcecours",
            name="date_limite_remise_physique",
            field=models.DateField(
                blank=True,
                help_text="Date limite à laquelle les étudiants doivent remettre leur travail physique (pour TP/TD)",
                null=True,
                verbose_name="Date limite de remise physique",
            ),
        ),
        migrations.AddField(
            model_name="supportpedagogiqueapprenant",
            name="date_limite_remise_physique",
            field=models.DateField(
                blank=True,
                help_text="Date limite pour la remise physique en main propre du travail",
                null=True,
                verbose_name="Date limite de remise physique",
            ),
        ),
    ]
