# Generated by Django 5.0.2 on 2026-08-18 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0010_ressourcecours_date_limite_remise_physique_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploiDuTempsApprenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre du planning"),
                ),
                (
                    "type_formation",
                    models.CharField(
                        choices=[
                            ("CERTIFICATION", "Formation de Certification"),
                            ("CONTINUE", "Formation Continue"),
                            ("TOUS", "Toutes les Formations"),
                        ],
                        default="TOUS",
                        max_length=20,
                        verbose_name="Type de formation",
                    ),
                ),
                (
                    "module_formation",
                    models.CharField(
                        choices=[
                            ("SECRETARIAT", "Secrétariat bureautique et comptable"),
                            ("MARKETING", "Marketing digital"),
                            ("INFOGRAPHIE", "Infographie"),
                            ("MAINTENANCE", "Maintenance informatique"),
                            ("RESEAUX", "Réseaux informatiques"),
                            ("WEBMASTER", "Webmaster"),
                            ("MIJEF", "Formation continue MIJEF 2035"),
                            ("TOUS", "Tous les Modules"),
                        ],
                        default="TOUS",
                        max_length=50,
                        verbose_name="Module de formation",
                    ),
                ),
                (
                    "niveau_etude",
                    models.CharField(
                        blank=True,
                        help_text="Laisser vide si applicable à tous les apprenants",
                        max_length=100,
                        verbose_name="Niveau d'étude / Stade",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "fichier_pdf",
                    models.FileField(
                        upload_to="emplois_du_temps_apprenants/",
                        verbose_name="Fichier PDF de l'emploi du temps",
                    ),
                ),
                (
                    "est_publie",
                    models.BooleanField(default=True, verbose_name="Publié & Actif"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emplois_apprenants_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emploi du Temps Apprenant",
                "verbose_name_plural": "Emplois du Temps Apprenants",
                "ordering": ["-date_debut", "-date_creation"],
            },
        ),
    ]
