# Generated by Django 5.0.2 on 2026-08-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0011_emploidutempsapprenant"),
        ("etudiants", "0006_etudiant_date_concours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatiereFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=150, verbose_name="Intitulé de la matière"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Code / Réf"
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=3,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Est active"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matieres",
                        to="etudiants.formation",
                        verbose_name="Formation rattachée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière de Formation",
                "verbose_name_plural": "Matières de Formation",
                "ordering": ["formation", "nom"],
                "unique_together": {("formation", "nom")},
            },
        ),
    ]
