# Generated by Django 5.0.2 on 2026-08-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0012_matiereformation"),
        ("etudiants", "0007_etudiant_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressourcecours",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ressources",
                to="etudiants.filiere",
                verbose_name="Filière",
            ),
        ),
        migrations.AddField(
            model_name="ressourcecours",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ressources",
                to="etudiants.niveau",
                verbose_name="Niveau",
            ),
        ),
    ]
