# Generated by Django 5.0.2 on 2026-08-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0013_ressourcecours_filiere_ressourcecours_niveau"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressourcecours",
            name="salle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ressources",
                to="cours.salle",
                verbose_name="Salle / Classe",
            ),
        ),
    ]
