# Generated by Django 5.0.2 on 2026-08-29 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0014_ressourcecours_salle"),
        ("professeurs", "0002_professeur_est_actif"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FichePresenceEnseignantHebdo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semaine_du", models.DateField(verbose_name="Semaine du (Lundi)")),
                ("semaine_au", models.DateField(verbose_name="Semaine au (Samedi)")),
                (
                    "annee_academique",
                    models.CharField(default="2025-2026", max_length=9),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé & Archivé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "rempli_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiches_enseignants_remplies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche Hebdo Présence Enseignant",
                "verbose_name_plural": "Fiches Hebdo Présence Enseignants",
                "ordering": ["-semaine_du"],
                "unique_together": {("semaine_du",)},
            },
        ),
        migrations.CreateModel(
            name="PointagePresenceEnseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_seance", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PRESENT", "✅ Présent (Séance effectuée)"),
                            ("ABSENT", "❌ Absent (Non effectuée)"),
                            ("EXCUSE", "🟡 Excusé / Remplacement"),
                            ("NON_DEFINI", "⏳ En attente de pointage"),
                        ],
                        default="NON_DEFINI",
                        max_length=20,
                    ),
                ),
                (
                    "heures_effectuees",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
                ),
                ("observations", models.CharField(blank=True, max_length=255)),
                (
                    "creneau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages_enseignant",
                        to="cours.creneauemploidutemps",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages_presence",
                        to="professeurs.professeur",
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="cours.fichepresenceenseignanthebdo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage Présence Enseignant",
                "verbose_name_plural": "Pointages Présence Enseignants",
                "unique_together": {("fiche", "enseignant", "creneau", "date_seance")},
            },
        ),
    ]
