# Generated by Django 5.0.2 on 2026-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_fichepresenceenseignanthebdo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutempshebdomadaire',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='emplois_du_temps/'),
        ),
    ]
