# Generated by Django 5.0.2 on 2026-07-09 11:34

import apps.professeurs.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Professeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(default="Camerounaise", max_length=50),
                ),
                (
                    "telephone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{9,15}$", "Numéro de téléphone invalide"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("adresse", models.TextField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("ASSISTANT", "Assistant"),
                            ("MAITRE_CONF", "Maître de Conférences"),
                            ("PROFESSEUR", "Professeur"),
                            ("VACATAIRE", "Vacataire"),
                            ("EXPERT", "Expert Professionnel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specialite",
                    models.CharField(help_text="Domaine de spécialité", max_length=200),
                ),
                ("diplomes", models.TextField(help_text="Liste des diplômes obtenus")),
                ("annee_experience", models.PositiveIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("CONGE", "En Congé"),
                            ("DETACHE", "Détaché"),
                            ("RETRAITE", "Retraité"),
                            ("SUSPENDU", "Suspendu"),
                        ],
                        default="ACTIF",
                        max_length=10,
                    ),
                ),
                ("date_embauche", models.DateField()),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "Contrat à Durée Indéterminée"),
                            ("CDD", "Contrat à Durée Déterminée"),
                            ("VACATAIRE", "Vacataire"),
                        ],
                        default="CDI",
                        max_length=20,
                    ),
                ),
                (
                    "salaire_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.professeurs.models.photo_professeur_path,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professeurs",
                        to="professeurs.departement",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profil_professeur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professeur",
                "verbose_name_plural": "Professeurs",
                "ordering": ["nom", "prenom"],
                "permissions": [
                    (
                        "peut_exporter_professeurs",
                        "Peut exporter la liste des professeurs",
                    ),
                    ("peut_voir_salaires", "Peut voir les informations salariales"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentProfesseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("DIPLOME", "Diplôme"),
                            ("CV", "Curriculum Vitae"),
                            ("CNI", "Carte Nationale d'Identité"),
                            ("CONTRAT", "Contrat de Travail"),
                            ("CERTIFICAT", "Certificat de Travail"),
                            ("AUTRE", "Autre Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fichier", models.FileField(upload_to="professeurs/documents/")),
                ("description", models.TextField(blank=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="professeurs.professeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Professeur",
                "verbose_name_plural": "Documents Professeurs",
                "ordering": ["-date_ajout"],
            },
        ),
        migrations.CreateModel(
            name="DisponibiliteProfesseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("LUN", "Lundi"),
                            ("MAR", "Mardi"),
                            ("MER", "Mercredi"),
                            ("JEU", "Jeudi"),
                            ("VEN", "Vendredi"),
                            ("SAM", "Samedi"),
                        ],
                        max_length=3,
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("est_disponible", models.BooleanField(default=True)),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilites",
                        to="professeurs.professeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilité Professeur",
                "verbose_name_plural": "Disponibilités Professeurs",
                "ordering": ["jour", "heure_debut"],
            },
        ),
        migrations.AddField(
            model_name="departement",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departement_dirige",
                to="professeurs.professeur",
            ),
        ),
        migrations.CreateModel(
            name="ChargeHoraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2024-2025", max_length=9),
                ),
                ("heures_assignees", models.PositiveIntegerField(default=0)),
                ("heures_effectuees", models.PositiveIntegerField(default=0)),
                ("heures_supplementaires", models.PositiveIntegerField(default=0)),
                (
                    "taux_horaire",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("est_paye", models.BooleanField(default=False)),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges_horaires",
                        to="professeurs.professeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charge Horaire",
                "verbose_name_plural": "Charges Horaires",
                "ordering": ["-annee_academique"],
                "unique_together": {("professeur", "annee_academique")},
            },
        ),
    ]
