# Generated by Django 5.0.2 on 2026-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professeurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professeur",
            name="est_actif",
            field=models.BooleanField(
                default=True, verbose_name="Compte actif (Soft Delete)"
            ),
        ),
    ]
