# Generated by Django 5.0.2 on 2026-07-09 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiants", "0002_alter_documentetudiant_valide_par"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnneeAcademique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=9, unique=True, verbose_name="Code"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "est_actuelle",
                    models.BooleanField(
                        default=False, verbose_name="Est l'année actuelle"
                    ),
                ),
                (
                    "est_ouverte_inscription",
                    models.BooleanField(
                        default=False, verbose_name="Inscriptions ouvertes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Année Académique",
                "verbose_name_plural": "Années Académiques",
                "ordering": ["-code"],
            },
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_inscription",
                    models.CharField(
                        choices=[
                            ("NOUVELLE", "Nouvelle Inscription"),
                            ("REINSCRIPTION", "Réinscription"),
                            ("TRANSFERT", "Transfert"),
                        ],
                        default="NOUVELLE",
                        max_length=15,
                        verbose_name="Type d'inscription",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PREINSCRIPTION", "Pré-inscription"),
                            ("EN_ATTENTE", "En Attente de Validation"),
                            ("COMPLETEE", "Complétée"),
                            ("VALIDEE", "Validée"),
                            ("REJETEE", "Rejetée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="PREINSCRIPTION",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_inscription",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "recu_preinscription",
                    models.FileField(
                        blank=True,
                        help_text="Téléversez le reçu de paiement de la pré-inscription (format PDF, JPG, PNG)",
                        null=True,
                        upload_to="inscriptions/recus/preinscription/%Y/%m/",
                        verbose_name="Reçu de pré-inscription",
                    ),
                ),
                (
                    "recu_preinscription_valide",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez après vérification manuelle du reçu",
                        verbose_name="Reçu de pré-inscription validé",
                    ),
                ),
                (
                    "recu_tranche_1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="inscriptions/recus/tranches/%Y/%m/",
                        verbose_name="Reçu 1ère Tranche",
                    ),
                ),
                (
                    "recu_tranche_1_valide",
                    models.BooleanField(
                        default=False, verbose_name="1ère Tranche validée"
                    ),
                ),
                (
                    "recu_tranche_2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="inscriptions/recus/tranches/%Y/%m/",
                        verbose_name="Reçu 2ème Tranche",
                    ),
                ),
                (
                    "recu_tranche_2_valide",
                    models.BooleanField(
                        default=False, verbose_name="2ème Tranche validée"
                    ),
                ),
                (
                    "recu_tranche_3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="inscriptions/recus/tranches/%Y/%m/",
                        verbose_name="Reçu 3ème Tranche",
                    ),
                ),
                (
                    "recu_tranche_3_valide",
                    models.BooleanField(
                        default=False, verbose_name="3ème Tranche validée"
                    ),
                ),
                (
                    "documents_complets",
                    models.BooleanField(
                        default=False, verbose_name="Documents complets"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "annee_academique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions",
                        to="inscriptions.anneeacademique",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions",
                        to="etudiants.filiere",
                        verbose_name="Filière choisie",
                    ),
                ),
                (
                    "validee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscriptions_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-date_inscription"],
                "permissions": [
                    ("peut_valider_inscriptions", "Peut valider les inscriptions"),
                    ("peut_valider_recus", "Peut valider les reçus de paiement"),
                    ("peut_exporter_inscriptions", "Peut exporter les inscriptions"),
                ],
                "unique_together": {("etudiant", "annee_academique")},
            },
        ),
        migrations.CreateModel(
            name="HistoriqueInscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("MODIFICATION", "Modification"),
                            ("VALIDATION", "Validation"),
                            ("REJET", "Rejet"),
                            ("ANNULATION", "Annulation"),
                            ("RECU_TELEVERSE", "Reçu téléversé"),
                            ("RECU_VALIDE", "Reçu validé"),
                            ("DOCUMENT_AJOUTE", "Document ajouté"),
                            ("DOCUMENT_VALIDE", "Document validé"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                ("details", models.TextField(verbose_name="Détails")),
                (
                    "date_action",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de l'action"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="inscriptions.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'inscription",
                "verbose_name_plural": "Historiques d'inscription",
                "ordering": ["-date_action"],
            },
        ),
        migrations.CreateModel(
            name="DocumentInscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("EXTRAIT_NAISSANCE", "Extrait de Naissance"),
                            ("CNI", "Carte Nationale d'Identité"),
                            ("PASSEPORT", "Passeport"),
                            ("BAC", "Diplôme BAC"),
                            ("RELEVE_BAC", "Relevé de Notes BAC"),
                            ("PHOTO", "Photo d'Identité"),
                            ("CERTIFICAT_MEDICAL", "Certificat Médical"),
                            ("CV", "Curriculum Vitae"),
                            ("LETTRE_MOTIVATION", "Lettre de Motivation"),
                            ("RECOMMANDATION", "Lettre de Recommandation"),
                            ("AUTRE", "Autre Document"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="inscriptions/documents/%Y/%m/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "est_valide",
                    models.BooleanField(default=False, verbose_name="Document validé"),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="inscriptions.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'Inscription",
                "verbose_name_plural": "Documents d'Inscription",
                "ordering": ["-date_ajout"],
            },
        ),
    ]
