# Generated by Django 5.0.2 on 2026-07-12 23:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0004_formation_apprenant"),
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bourse",
                    models.CharField(
                        choices=[
                            ("EXCELLENCE", "Bourse d'Excellence (100%)"),
                            ("DEMI_EXCELLENCE", "Demi-Bourse d'Excellence (50%)"),
                            ("SOCIALE", "Aide Sociale"),
                            (
                                "EXONERATION_PARTIELLE",
                                "Exonération Partielle (Montant spécifique)",
                            ),
                            ("PARTENARIAT", "Réduction Partenariat"),
                        ],
                        default="EXCELLENCE",
                        max_length=30,
                        verbose_name="Type de bourse",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Montant de la bourse (FCFA)",
                    ),
                ),
                (
                    "date_attribution",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'attribution",
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Bourse active"),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire / Motif"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "annee_academique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bourses",
                        to="inscriptions.anneeacademique",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bourses",
                        to="etudiants.etudiant",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bourse d'études",
                "verbose_name_plural": "Bourses d'études",
                "ordering": ["-date_attribution"],
                "unique_together": {("etudiant", "annee_academique")},
            },
        ),
    ]
