# Generated by Django 5.0.2 on 2026-08-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0006_etudiant_date_concours_and_more"),
        ("inscriptions", "0002_bourse"),
        ("paiements", "0007_alter_recupaiement_tranche"),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheRenseignement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_validee_ia",
                    models.BooleanField(
                        default=False, verbose_name="Photo validée par IA"
                    ),
                ),
                (
                    "recu_valide_ia",
                    models.BooleanField(
                        default=False, verbose_name="Reçu validé par IA"
                    ),
                ),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("VALIDE", "Validée (Auto IA / Scolarité)"),
                            (
                                "EN_ATTENTE_VERIFICATION",
                                "En Attente de Vérification (Comptabilité)",
                            ),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="EN_ATTENTE_VERIFICATION",
                        max_length=30,
                        verbose_name="Statut de validation",
                    ),
                ),
                (
                    "details_ia_photo",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Détails IA Photo"
                    ),
                ),
                (
                    "details_ia_recu",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Détails IA Reçu"
                    ),
                ),
                (
                    "message_ia",
                    models.TextField(
                        blank=True, default="", verbose_name="Message de l'Agent IA"
                    ),
                ),
                (
                    "date_soumission",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de soumission"
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "annee_academique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiches_renseignement",
                        to="inscriptions.anneeacademique",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_renseignement",
                        to="etudiants.etudiant",
                        verbose_name="Étudiant",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiches_renseignement",
                        to="inscriptions.inscription",
                        verbose_name="Inscription associée",
                    ),
                ),
                (
                    "recu_paiement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiches_renseignement",
                        to="paiements.recupaiement",
                        verbose_name="Reçu de paiement associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de Renseignement",
                "verbose_name_plural": "Fiches de Renseignement",
                "ordering": ["-date_soumission"],
            },
        ),
    ]
