# Generated by Django 5.0.2 on 2026-08-18 20:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0006_etudiant_date_concours_and_more"),
        ("inscriptions", "0003_ficherenseignement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificatScolarite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_reference",
                    models.CharField(
                        help_text="Format: IAI-CS-2026-XXXXXX",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de référence",
                    ),
                ),
                (
                    "token_verification",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token de vérification",
                    ),
                ),
                (
                    "date_delivrance",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de délivrance",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        default="Usage administratif",
                        max_length=150,
                        verbose_name="Motif / Usage",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("VALIDE", "🟢 Valide"),
                            ("ANNULE", "🔴 Annulé / Révoqué"),
                            ("EXPIRE", "⚪ Expiré"),
                        ],
                        default="VALIDE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "derogation_accordee",
                    models.BooleanField(
                        default=False, verbose_name="Dérogation administrative accordée"
                    ),
                ),
                (
                    "motif_derogation",
                    models.TextField(
                        blank=True, default="", verbose_name="Motif de la dérogation"
                    ),
                ),
                (
                    "hash_securite",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Empreinte cryptographique (SHA-256)",
                    ),
                ),
                (
                    "telechargements_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Nombre de consultations/téléchargements",
                    ),
                ),
                (
                    "annee_academique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificats_scolarite",
                        to="inscriptions.anneeacademique",
                        verbose_name="Année Académique",
                    ),
                ),
                (
                    "emetteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificats_emis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Émis par (Agent)",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificats_scolarite",
                        to="etudiants.etudiant",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat de Scolarité",
                "verbose_name_plural": "Certificats de Scolarité",
                "ordering": ["-date_delivrance"],
            },
        ),
    ]
